# Nome da pipeline/ workflow
name: pipeline-exemplo

# Gatilho para execução da pipeline
# gatilho manual = workflow_dispatch
# gatilho automático = pull_request (dispara a pipeline quando um PR é aberto/atualizado para a master)

on:
    workflow_dispatch:
    pull_request:
        branches:
            - master

# tarefas/ jobs da pipeline
jobs:
    # nome do job
    testes:

        # configuração de máquina onde o job será executado
        runs-on: ubuntu-latest

        # passos do job
        steps:

            # clone dos arquivos do repositório para a máquina do job
            - uses: actions/checkout@v4

            # instalação do node.js
            - uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: Instalação das dependências do projeto
              run: npm install

            - name: Execução dos testes unitários
              run: npm test

            - name: Build do projeto
              run: npm run build

            - name: Instalação dos browsers do Playwright
              run: npx playwright install

            - name: Execução dos testes e2e
              run: npm run test:e2e

            # upload do relatório de execução dos testes e2e do Playwright como artifact da pipeline
            - name: Upload do relatório de testes E2E (Playwright)
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30
